# GLYCINE
GGG: G
GGU: G
GGA: G
GGC: G
# VALINE
GUG: V
GUU: V
GUA: V
GUC: V
# GLUTAMIC ACID
GAG: E
# ASPARTIC ACID
GAU: D
# GLUTAMIC ACID
GAA: E
# ASPARTIC ACID
GAC: D
# ALANINE
GCG: A
GCU: A
GCA: A
GCC: A
# TRYPTOPHAN
UGG: W
# CYSTEINE
UGU: C
# STOP CODON
UGA: •
# CYSTEINE
UGC: C
# LEUCINE
UUG: L
# PHENYLALANINE
UUU: F
# LEUCINE
UUA: L
# PHENYLALANINE
UUC: F
# STOP CODON
UAG: •
# TYROSINE
UAU: Y
# STOP CODON
UAA: •
# TYROSINE
UAC: Y
# SERINE
UCG: S
UCU: S
UCA: S
UCC: S
# ARGININE
AGG: R
# SERINE
AGU: S
# ARGININE
AGA: R
# SERINE
AGC: S
# METHIONINE
AUG: M
# ISOLEUCINE
AUU: I
AUA: I
AUC: I
# LYSINE
AAG: K
# ASPARAGINE
AAU: N
# LYSINE
AAA: K
# ASPARAGINE
AAC: N
# THREONINE
ACG: T
ACU: T
ACA: T
ACC: T
# ARGININE
CGG: R
CGU: R
CGA: R
CGC: R
# LEUCINE
CUG: L
CUU: L
CUA: L
CUC: L
# GLUTAMINE
CAG: O
# HISTIDINE
CAU: H
# GLUTAMINE
CAA: O
# HISTIDINE
CAC: H
# PROLINE
CCG: P
CCU: P
CCA: P
CCC: P